name: uni_map_platform_interface
description: Uni Map Platform Interface.
version: 0.7.0-rc.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  foundation_fluttify:
    git:
      url: https://github.com/EchoPuda/foundation_fluttify.git
  core_location_fluttify:
    git:
      url: https://github.com/EchoPuda/core_location_fluttify.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4